"""
Advanced Pattern Expansion Script
Adds many natural language variations to under-resourced intents so that
any wording from the user can be matched.
"""

import json
import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
INTENTS_FILE = os.path.join(BASE_DIR, "..", "intents", "intents_en.json")

# New patterns to add per intent tag
EXTRA_PATTERNS = {
    "Oriental_Mindoro_Overview": [
        "mindoro oriental",
        "tell me about mindoro",
        "what is mindoro",
        "mindoro island",
        "mindoro province",
        "mindoro philippines",
        "province of mindoro",
        "oriental mindoro island",
        "explore oriental mindoro",
        "visit oriental mindoro",
        "travel to oriental mindoro",
        "things about oriental mindoro",
        "what can i find in oriental mindoro",
        "is oriental mindoro a good destination",
        "how is oriental mindoro",
        "mindoro travel",
        "mindoro tourist destination",
        "info on oriental mindoro",
        "give me info about oriental mindoro",
        "can you describe oriental mindoro",
        "oriental mindoro region",
        "mimaropa oriental mindoro",
        "where exactly is oriental mindoro",
        "oriental mindoro location",
        "i want to know about oriental mindoro",
        "learning about oriental mindoro",
        "what makes oriental mindoro special",
        "why visit oriental mindoro",
        "reasons to visit oriental mindoro",
        "beauty of oriental mindoro",
        "nature in oriental mindoro",
        "culture of oriental mindoro",
        "history and culture of oriental mindoro",
        "tourist destination oriental mindoro",
        "places to explore in oriental mindoro",
        "what is special about oriental mindoro",
        "about the province",
        "the province",
        "province info",
        "mindoro facts",
        "oriental mindoro geography",
        "size of oriental mindoro",
        "population of oriental mindoro",
        "capital of oriental mindoro",
        "what is the capital of oriental mindoro",
        "what region is oriental mindoro in",
        "oriental mindoro features",
        "what does the province offer",
        "highlights of oriental mindoro",
        "things oriental mindoro is known for",
        "what oriental mindoro is famous for",
        "famous places in oriental mindoro",
        "mindoro adventure",
        "adventure in oriental mindoro",
        "natural wonders oriental mindoro",
        "natural beauty oriental mindoro",
        "what is oriantal mindoro",
        "tell me bout mindoro",
        "mindoro info",
    ],

    "All_Municipalities": [
        "all municipalities in oriental mindoro",
        "list of municipalities in oriental mindoro",
        "name all municipalities in oriental mindoro",
        "complete list of towns in oriental mindoro",
        "what are all the towns in oriental mindoro",
        "how many towns does oriental mindoro have",
        "all towns in mindoro",
        "name the towns in oriental mindoro",
        "what places are in oriental mindoro",
        "places in oriental mindoro",
        "all places in mindoro",
        "how many places in oriental mindoro",
        "towns and cities in oriental mindoro",
        "mga bayan sa oriental mindoro",
        "ano ang mga bayan sa oriental mindoro",
        "ilang bayan ang nasa oriental mindoro",
        "listahan ng mga bayan sa oriental mindoro",
        "munisipalidad ng oriental mindoro",
        "list the municipalities",
        "give me a list of all towns",
        "show me all the municipalities",
        "how many municipalities does oriental mindoro have",
        "14 municipalities of oriental mindoro",
        "what are the 14 municipalities",
        "name the 14 towns",
        "cities of oriental mindoro",
        "barangay in oriental mindoro",
        "local government units oriental mindoro",
        "all lgus oriental mindoro",
        "complete list ofmunicipalities",
        "municipalities list oriental mindoro",
        "towns list mindoro",
        "all cities and towns",
        "every town in oriental mindoro",
        "each municipality in oriental mindoro",
        "list every municipality",
        "tell me all the towns",
        "what towns exist in oriental mindoro",
        "towns that make up oriental mindoro",
        "municipalities that are in oriental mindoro",
        "baco bongabong bulalacao calapan",
    ],

    "Puerto_Galera_Info": [
        "pg beach",
        "puerto galera info",
        "what is there to do in puerto galera",
        "what to see in puerto galera",
        "puerto galera sightseeing",
        "best places in puerto galera",
        "visiting puerto galera",
        "trip to puerto galera",
        "puerto galera vacation",
        "going to puerto galera",
        "i want to visit puerto galera",
        "is puerto galera worth visiting",
        "why go to puerto galera",
        "highlights of puerto galera",
        "places to visit in puerto galera",
        "things to experience in puerto galera",
        "puerto galera diving spots",
        "dive sites puerto galera",
        "snorkeling in puerto galera",
        "island hopping puerto galera",
        "puerto galera day tour",
        "weekend in puerto galera",
        "backpacking puerto galera",
        "budget trip to puerto galera",
        "how much to go to puerto galera",
        "ferry to puerto galera",
        "how to reach puerto galera",
        "batangas to puerto galera",
        "boat to puerto galera",
        "bus to puerto galera",
        "puerto galera accommodation",
        "where to stay in puerto galera",
        "resort recommendations puerto galera",
        "cheap hotels puerto galera",
        "luxury resort puerto galera",
        "food in puerto galera",
        "restaurants in puerto galera",
        "best food puerto galera",
        "what to eat in puerto galera",
        "sabang beach activities",
        "white beach pg",
        "big la laguna beach",
        "small la laguna beach",
        "coco beach puerto galera",
        "tamaraw beach",
        "talipanan beach",
        "what beach should i go to in puerto galera",
        "famous waterfalls puerto galera",
        "tukuran waterfall",
        "tamaraw waterfall",
        "hot springs puerto galera",
        "mangyan village puerto galera",
        "puerto galera nightlife",
        "bars in sabang",
        "apo reef how to get there",
        "verde island diving",
        "best coral reef philippines",
        "swimming in puerto galera",
        "is the water clear in puerto galera",
        "what month to visit puerto galera",
        "holy week puerto galera",
        "puertogalera",
        "p galera",
        "pueto galera",
    ],

    "Calapan_Info": [
        "calapan",
        "info on calapan",
        "about calapan city",
        "visiting calapan",
        "things to do in calapan city",
        "places to see in calapan city",
        "what is there in calapan",
        "calapan sightseeing",
        "i want to visit calapan",
        "trip to calapan",
        "calapan city tourism",
        "tourist spots calapan",
        "what is calapan known for",
        "best places calapan",
        "highlights of calapan",
        "calapan attractions to visit",
        "where to go in calapan",
        "what to experience in calapan",
        "calapan heritage sites",
        "cathedral in calapan",
        "sto nino church calapan",
        "old church calapan",
        "historical sites calapan",
        "museum in calapan",
        "heritage museum calapan",
        "market in calapan",
        "calapan public market",
        "malls in calapan",
        "shopping calapan",
        "food in calapan",
        "restaurants calapan",
        "where to eat in calapan city",
        "best food calapan",
        "seafood calapan",
        "carinderia calapan",
        "calapan port",
        "port of calapan",
        "batangas calapan ferry",
        "ferry terminal calapan",
        "how to get to calapan",
        "hotel in calapan",
        "accommodation calapan",
        "where to stay calapan",
        "provincial capital",
        "capital city of oriental mindoro",
        "capital of oriental mindoro",
        "heart of oriental mindoro",
        "main city oriental mindoro",
        "waterfall near calapan",
        "mambuaya falls how to get there",
        "inarawan falls calapan",
        "festival in calapan",
        "sinadya calapan",
        "kalipan",
        "calapn city",
    ],

    "Baco_Info": [
        "baco",
        "baco municipality",
        "baco oriental mindoro tourism",
        "what is in baco",
        "interesting places in baco",
        "things to do in baco",
        "tourist destination baco",
        "visiting baco oriental mindoro",
        "trip to baco",
        "i want to go to baco",
        "what can i do in baco",
        "baco travel guide",
        "attractions in baco",
        "where to go in baco",
        "baco eco adventure",
        "baco river",
        "river in baco",
        "swimming in baco",
        "nature in baco",
        "forest in baco",
        "mountain in baco",
        "mount halcon trail",
        "how to climb mount halcon",
        "mt halcon hiking",
        "mount halcon difficulty",
        "mount halcon guide",
        "mount halcon trek",
        "halcon mountain",
        "climbing halcon",
        "tallest peak oriental mindoro",
        "highest mountain oriental mindoro",
        "baco adventure",
        "eco tour baco",
        "wildlife in baco",
        "birds baco",
        "baco camping",
        "camping near calapan",
        "camping oriental mindoro",
        "resort in baco",
        "accommodation baco",
        "hotel baco",
        "food baco",
        "how to get to baco",
        "bako oriental mindoro",
        "mnt halcon",
    ],

    "Other_Municipalities_Info": [
        "bongabong",
        "what is in bongabong",
        "things to see in bongabong",
        "bongabong travel",
        "malugay falls bongabong",
        "kuta shrine",
        "bongabong eco park",
        "bulalacao",
        "things to do in bulalacao",
        "tambaron island bulalacao",
        "suguicay island",
        "island in bulalacao",
        "beach in bulalacao",
        "gloria oriental mindoro",
        "what to see in gloria",
        "malpoc falls gloria",
        "bighani farm gloria",
        "mansalay oriental mindoro",
        "things to do in mansalay",
        "mansalay mangyan",
        "mangyan in mansalay",
        "amnay fossil site",
        "fossil site mansalay",
        "pinamalayan oriental mindoro",
        "what to see in pinamalayan",
        "dapdap beach pinamalayan",
        "kuta falls pinamalayan",
        "pinamalayan beach",
        "pola oriental mindoro",
        "things to do in pola",
        "pola eco farm",
        "pula river pola",
        "infinity farm pola",
        "roxas oriental mindoro",
        "baybay beach roxas",
        "st peter church roxas",
        "villa sylvina roxas",
        "what to see in roxas",
        "san teodoro",
        "san teodoro falls",
        "dulangan river",
        "hidden paradise san teodoro",
        "socorro oriental mindoro",
        "socorro attractions",
        "socorro lake",
        "victoria oriental mindoro",
        "halcon base camp victoria",
        "adventure in victoria",
        "streams in victoria",
        "which municipalities have beaches",
        "municipalities with waterfalls",
        "best municipality to visit",
        "small towns oriental mindoro",
        "lesser known towns mindoro",
        "off the beaten path mindoro",
        "hidden gems oriental mindoro",
        "bongabng",
        "bulaklao",
    ],

    "Transportation_How_To_Get_There": [
        "how do i get to oriental mindoro",
        "what is the way to oriental mindoro",
        "going to oriental mindoro",
        "traveling to oriental mindoro",
        "transport to oriental mindoro",
        "route to oriental mindoro",
        "directions to oriental mindoro",
        "how do i go to mindoro",
        "how to arrive at oriental mindoro",
        "how can i reach oriental mindoro",
        "what transport goes to mindoro",
        "public transport to mindoro",
        "commute to mindoro",
        "bus going to mindoro",
        "how to go from manila to mindoro",
        "manila to oriental mindoro",
        "from manila to calapan",
        "pasay to mindoro",
        "buendia to mindoro",
        "bus station to mindoro",
        "batangas pier directions",
        "how to get to batangas pier",
        "batangas pier bus",
        "ferry from batangas to calapan",
        "roro ferry mindoro",
        "fastcraft to calapan",
        "passenger ferry mindoro",
        "boat ride to mindoro",
        "ferry schedule batangas calapan",
        "ferry time batangas to calapan",
        "ferry fare batangas calapan",
        "how long is the ferry to calapan",
        "ferry duration mindoro",
        "montenegro lines",
        "starlite ferries",
        "archipelago ferries",
        "2go ferry mindoro",
        "how to travel from calapan to other towns",
        "bus calapan to naujan",
        "van calapan to puerto galera",
        "transportation within oriental mindoro",
        "getting around inside mindoro",
        "local transport mindoro",
        "jeep to naujan",
        "tricycle fare mindoro",
        "how to go to puerto galera from manila",
        "fastest way to puerto galera",
        "boat from batangas to puerto galera",
        "direct boat puerto galera",
        "si cat boat puerto galera",
        "paano pumunta sa oriental mindoro",
        "paano makakarating sa mindoro",
        "route papunta sa mindoro",
        "kung paano makapunta sa mindoro",
        "transport papunta sa naujan",
        "how 2 get 2 mindoro",
        "hw do i get there",
        "where can i take the boat",
    ],

    "Local_Transport": [
        "how do i move around in oriental mindoro",
        "ways to get around in mindoro",
        "modes of transport in oriental mindoro",
        "public transportation inside mindoro",
        "commuting inside mindoro",
        "local vehicles in oriental mindoro",
        "jeepney routes mindoro",
        "van for hire mindoro",
        "multicab mindoro",
        "habal habal mindoro",
        "motorbike taxi mindoro",
        "tricycle rates mindoro",
        "kalesa mindoro",
        "cheap transport oriental mindoro",
        "affordable way to get around mindoro",
        "rent a car mindoro",
        "car rental oriental mindoro",
        "motorbike rental mindoro",
        "bicycle in oriental mindoro",
        "how to commute in calapan",
        "jeep in calapan",
        "tricycle calapan routes",
        "van calapan to baco",
        "van calapan to naujan",
        "jeep naujan to calapan",
        "how much is the tricycle",
        "fare tricycle mindoro",
        "jeepney fare mindoro",
        "van fare mindoro",
        "getting around in puerto galera",
        "transport within puerto galera",
        "how to get around sabang",
        "private boat puerto galera",
        "pump boat mindoro",
        "bangka mindoro",
        "how to island hop in mindoro",
        "island hopping transport",
        "boat transfer mindoro",
        "how to move between municipalities",
        "travel between towns oriental mindoro",
        "bus schedule oriental mindoro",
        "van schedule mindoro",
        "when does the last jeep leave",
        "terminal in calapan",
        "van terminal calapan",
        "north bus terminal mindoro",
        "paano gumalaw sa oriental mindoro",
        "how 2 move around mindoro",
    ],

    "Local_Food_Cuisine": [
        "food in mindoro",
        "mindoro food",
        "what does mindoro eat",
        "mindoro specialty food",
        "oriental mindoro food specialty",
        "best dish in oriental mindoro",
        "traditional food oriental mindoro",
        "native food mindoro",
        "authentic mindoro cuisine",
        "what is the local food",
        "local dish mindoro",
        "famous dish mindoro",
        "try food in oriental mindoro",
        "must eat in oriental mindoro",
        "food experience oriental mindoro",
        "what food should i try in mindoro",
        "delicious food in mindoro",
        "mindoro specialties",
        "seafood mindoro",
        "fresh seafood oriental mindoro",
        "fish in oriental mindoro",
        "grilled fish mindoro",
        "shellfish mindoro",
        "lobster mindoro",
        "squid oriental mindoro",
        "lapu lapu fish mindoro",
        "tuna oriental mindoro",
        "dried fish mindoro",
        "nasudan dried fish",
        "binagoongan mindoro",
        "kakanin oriental mindoro",
        "rice cake mindoro",
        "native rice cake",
        "tuba coconut wine mindoro",
        "coconut wine oriental mindoro",
        "mangyan food",
        "mangyan root crop dishes",
        "ubod mindoro",
        "where to eat in oriental mindoro",
        "food places oriental mindoro",
        "best restaurant mindoro",
        "carinderias mindoro",
        "cheap food mindoro",
        "affordable meals mindoro",
        "hawker food mindoro",
        "street food oriental mindoro",
        "breakfast mindoro",
        "lunch oriental mindoro",
        "dinner oriental mindoro",
        "carinderia near me mindoro",
        "restaurant recommendation calapan",
        "where to eat naujan",
        "night market mindoro",
        "food market oriental mindoro",
        "ano ang pagkain sa oriental mindoro",
        "masustansyang pagkain sa mindoro",
        "pagkain sa oriental mindoro",
        "what food 2 eat in mindoro",
        "mindoro delicasy",
    ],

    "Festivals_Events": [
        "events in oriental mindoro",
        "celebration in oriental mindoro",
        "local celebration mindoro",
        "upcoming events mindoro",
        "festival schedule oriental mindoro",
        "when are the local festivals",
        "what festivals happen in oriental mindoro",
        "what events are in oriental mindoro",
        "mindoro celebrations",
        "big events oriental mindoro",
        "summer events mindoro",
        "december events oriental mindoro",
        "christmas events mindoro",
        "new year mindoro",
        "holy week events mindoro",
        "sinadya sa halaran festival",
        "sinadya festival date",
        "when is sinadya sa halaran",
        "sinadya sa halaran calapan",
        "biggest festival oriental mindoro",
        "street dancing festival mindoro",
        "cultural show mindoro",
        "cultural festival oriental mindoro",
        "puerto galera foundation day",
        "puerto galera anniversary",
        "naujan fiesta",
        "naujan founding anniversary",
        "bongabong festival",
        "kuta festival bongabong",
        "town fiesta oriental mindoro",
        "patron saint fiesta mindoro",
        "religious festivals mindoro",
        "indigenous festival mindoro",
        "mangyan festival",
        "ambahan festival",
        "folk arts festival mindoro",
        "music festival mindoro",
        "dance festival mindoro",
        "food festival mindoro",
        "harvest festival mindoro",
        "fishing festival mindoro",
        "diving festival mindoro",
        "april events mindoro",
        "may events mindoro",
        "june events mindoro",
        "when to visit for festivals",
        "best time for festivals oriental mindoro",
        "pasko sa oriental mindoro",
        "pistang bayan mindoro",
        "kapistahan sa oriental mindoro",
        "what events 2 attend",
        "festvals in mindoro",
        "fiestas mindoro",
    ],

    "Diving_Water_Sports": [
        "dive in oriental mindoro",
        "best dive in oriental mindoro",
        "scuba in mindoro",
        "diving trip oriental mindoro",
        "i want to dive in mindoro",
        "snorkel in oriental mindoro",
        "snorkeling trip mindoro",
        "where to snorkel in oriental mindoro",
        "best snorkeling spot mindoro",
        "underwater in oriental mindoro",
        "sea activities oriental mindoro",
        "water sport mindoro",
        "ocean activities oriental mindoro",
        "beach activities mindoro",
        "swimming in the sea mindoro",
        "kayak oriental mindoro",
        "kayaking mindoro",
        "paddling mindoro",
        "surfing oriental mindoro",
        "surfing spots mindoro",
        "windsurfing mindoro",
        "kitesurfing mindoro",
        "parasailing mindoro",
        "jetski mindoro",
        "banana boat ride mindoro",
        "boat tour mindoro",
        "island hopping oriental mindoro",
        "hopping from island to island mindoro",
        "best island oriental mindoro",
        "uninhabited island mindoro",
        "marine sanctuary mindoro",
        "marine protected area mindoro",
        "coral garden mindoro",
        "apo reef how to visit",
        "apo reef national park",
        "how to go to apo reef",
        "apo reef location",
        "verde island passage biodiversity",
        "diving at verde island",
        "fish sanctuary oriental mindoro",
        "dolphins oriental mindoro",
        "shark in oriental mindoro",
        "manta ray mindoro",
        "sea turtle oriental mindoro",
        "whale shark mindoro",
        "dive shop calapan",
        "diving instructors mindoro",
        "dive course mindoro",
        "learn to dive mindoro",
        "padi course oriental mindoro",
        "diving packages mindoro",
        "affordable diving mindoro",
        "scubar diving",
        "snorkelling mindoro",
        "dving spots",
    ],

    "Beaches_Info": [
        "beach in oriental mindoro",
        "beaches to visit in oriental mindoro",
        "best beach in mindoro",
        "beautiful beaches oriental mindoro",
        "top beaches oriental mindoro",
        "beach destinations oriental mindoro",
        "beach vacation mindoro",
        "beach trip mindoro",
        "beach getaway mindoro",
        "i want to go to the beach in mindoro",
        "beach in puerto galera",
        "white sand beach mindoro",
        "white beach sabang",
        "small beach mindoro",
        "hidden beach mindoro",
        "peaceful beach mindoro",
        "crowded beach mindoro",
        "party beach mindoro",
        "family beach mindoro",
        "beach for swimming",
        "swimming beach mindoro",
        "clear water beach mindoro",
        "turquoise water beach mindoro",
        "long beach mindoro",
        "rocky beach mindoro",
        "lagoon mindoro",
        "beachside resort mindoro",
        "resort on the beach mindoro",
        "cheap beach resort mindoro",
        "luxury beach resort mindoro",
        "beach cottages mindoro",
        "beach camping mindoro",
        "dapdap beach pinamalayan visit",
        "baybay beach roxas how to get there",
        "beach at bulalacao",
        "sand bar mindoro",
        "mangrove beach mindoro",
        "sunset beach mindoro",
        "sunrise beach mindoro",
        "best beach sunset mindoro",
        "beach near calapan city",
        "beach hiking mindoro",
        "trek to beach mindoro",
        "accessible beach mindoro",
        "bich in mindoro",
        "beatch mindoro",
        "sand beach oriental mindoro",
    ],

    "Waterfalls_Info": [
        "waterfalls to visit in oriental mindoro",
        "best waterfall in mindoro",
        "waterfall near me oriental mindoro",
        "waterfall trip mindoro",
        "waterfall destination mindoro",
        "visit a waterfall mindoro",
        "i want to see a waterfall in mindoro",
        "beautiful waterfalls mindoro",
        "swimming at a waterfall mindoro",
        "waterfall swimming mindoro",
        "how to get to tamaraw falls",
        "tamaraw falls location",
        "tamaraw falls height",
        "tamaraw falls fees",
        "tukuran falls puerto galera",
        "tukuran falls hike",
        "mambuaya falls calapan",
        "how to reach mambuaya falls",
        "mambuaya falls hike",
        "malugay falls bongabong",
        "malugay falls location",
        "kuta falls pinamalayan",
        "inarawan falls location",
        "multiple tier waterfall mindoro",
        "hidden waterfall mindoro",
        "secret waterfall oriental mindoro",
        "big waterfall mindoro",
        "small waterfall mindoro",
        "clean waterfall mindoro",
        "freshwater falls mindoro",
        "cool off waterfall mindoro",
        "refreshing falls mindoro",
        "waterfall picnic mindoro",
        "nature trip waterfall mindoro",
        "hike to waterfall mindoro",
        "trail to waterfall mindoro",
        "waterfall near calapan",
        "waterfall near puerto galera",
        "waterfalls for kids mindoro",
        "waterfall entrance fee mindoro",
        "tamarau falls",
        "mambuwa falls",
        "waterfal mindoro",
        "water falls oriental mindoro",
    ],

    "Hiking_Trekking": [
        "hiking trail oriental mindoro",
        "trek in oriental mindoro",
        "mountain hike oriental mindoro",
        "hiking destinations mindoro",
        "best hike in oriental mindoro",
        "outdoor activities mindoro",
        "adventure outdoor mindoro",
        "mountain climbing mindoro",
        "nature trek mindoro",
        "guided hike mindoro",
        "hard hike mindoro",
        "easy hike mindoro",
        "beginner hike mindoro",
        "hike to waterfall mindoro",
        "mount halcon details",
        "mount halcon summit",
        "mount halcon difficulty level",
        "mount halcon registration",
        "mount halcon guide fee",
        "how long to climb mt halcon",
        "days to climb mount halcon",
        "is mount halcon hard",
        "mount halcon weather",
        "mount halcon camping",
        "highest peak mindoro",
        "adventure camping oriental mindoro",
        "overnight trek mindoro",
        "backpacking trail mindoro",
        "forest trail oriental mindoro",
        "jungle trek mindoro",
        "bird watching hike mindoro",
        "nature walk mindoro",
        "hiking guide mindoro",
        "local guide hike mindoro",
        "eco trail mindoro",
        "mangrove walk mindoro",
        "rice paddy walk mindoro",
        "mountain views mindoro",
        "scenic hike mindoro",
        "photography hike mindoro",
        "trekking boots mindoro",
        "what to bring hiking mindoro",
        "hiking preparation mindoro",
        "triking mindoro",
        "trekign mindoro",
        "hike near calapan",
        "hike near naujan",
    ],

    "Mangyan_Culture": [
        "mangyan people",
        "mangyan indigenous tribe",
        "who are the mangyan",
        "tell me about the mangyan",
        "mangyan tribes in mindoro",
        "types of mangyan tribes",
        "8 mangyan tribes",
        "hanunuo mangyan script",
        "mangyan writing system",
        "pre colonial script mindoro",
        "mangyan ambahan poetry",
        "mangyan traditional poetry",
        "mangyan basket weaving",
        "mangyan weaving",
        "mangyan textiles",
        "mangyan abaca crafts",
        "mangyan art",
        "mangyan jewelry",
        "mangyan handicrafts for sale",
        "fair trade mangyan products",
        "buying mangyan crafts",
        "where to see the mangyan",
        "visit mangyan village",
        "mangyan community tour",
        "mangyan settlement",
        "indigenous community mindoro",
        "native tribe mindoro",
        "tribal people mindoro",
        "cultural heritage tribe mindoro",
        "ethnography mindoro",
        "traditional life mangyan",
        "mangyan lifestyle",
        "mangyan dress costume",
        "traditional attire mangyan",
        "mangyan food",
        "root crops mangyan",
        "mangyan tradition",
        "mangyan belief",
        "mangyan language",
        "iraya mangyan",
        "alangan mangyan",
        "tau buid mangyan",
        "buhid mangyan",
        "hanunuo script recognized by unesco",
        "indigenous culture in mindoro",
        "manygan culture",
        "mangyan tibe",
        "mangyan peple",
    ],

    "Best_Time_To_Visit": [
        "when should i go to oriental mindoro",
        "good time to visit mindoro",
        "what month to go to mindoro",
        "best months to visit mindoro",
        "ideal time to visit oriental mindoro",
        "right time to visit oriental mindoro",
        "is it safe to visit mindoro in rainy season",
        "can i visit mindoro year round",
        "weather in oriental mindoro",
        "climate in oriental mindoro",
        "temperature in oriental mindoro",
        "humidity in oriental mindoro",
        "windy season oriental mindoro",
        "cold months oriental mindoro",
        "hot months oriental mindoro",
        "dry months oriental mindoro",
        "wet months oriental mindoro",
        "rain in oriental mindoro",
        "monsoon oriental mindoro",
        "typhoon in oriental mindoro",
        "typhoon season mindoro",
        "when is the rain in mindoro",
        "when does it rain in oriental mindoro",
        "amihan oriental mindoro",
        "habagat oriental mindoro",
        "northeast monsoon mindoro",
        "southwest monsoon mindoro",
        "summer in oriental mindoro",
        "december in oriental mindoro",
        "january visit mindoro",
        "february visit mindoro",
        "march visit mindoro",
        "april visit mindoro",
        "when is peak season mindoro",
        "what is peak season mindoro",
        "off peak mindoro",
        "off season visit mindoro",
        "budget season oriental mindoro",
        "avoid crowds mindoro",
        "best weather mindoro",
        "good weather to go diving mindoro",
        "ideal diving season mindoro",
        "beach season oriental mindoro",
        "swimming season mindoro",
        "is the sea calm in mindoro",
        "rough sea mindoro",
        "storm mindoro",
        "when 2 visit mindoro",
        "best tym 2 go mindoro",
        "bset time to visit",
    ],

    "Budget_Travel": [
        "how much does it cost to travel to mindoro",
        "total cost of trip to oriental mindoro",
        "cheap trip to oriental mindoro",
        "budget friendly oriental mindoro",
        "backpacker budget oriental mindoro",
        "how expensive is oriental mindoro",
        "is oriental mindoro affordable",
        "travel cost mindoro",
        "cost of living mindoro tourist",
        "daily expenses oriental mindoro",
        "how much should i budget for mindoro",
        "budget for 3 days in oriental mindoro",
        "3 day trip budget oriental mindoro",
        "weekend trip budget mindoro",
        "travel allowance mindoro",
        "estimated budget oriental mindoro",
        "budget breakdown oriental mindoro",
        "how much is the ferry fare",
        "ferry fare batangas to calapan cost",
        "ferry ticket price mindoro",
        "bus fare to batangas pier",
        "bus fare manila to batangas",
        "van fare calapan to naujan",
        "jeep fare oriental mindoro",
        "tricycle fare naujan",
        "how much is accommodation mindoro",
        "cheap hotel mindoro price",
        "budget hostel mindoro",
        "pension house price mindoro",
        "guesthouse rate mindoro",
        "beach resort rate mindoro",
        "food cost oriental mindoro",
        "how much is food in mindoro",
        "meals price oriental mindoro",
        "cheap meal mindoro",
        "street food cost mindoro",
        "entrance fee tourist spots mindoro",
        "tour package price mindoro",
        "guided tour cost mindoro",
        "diving cost mindoro",
        "island hopping price mindoro",
        "spending money mindoro",
        "save money in oriental mindoro",
        "how to travel on a budget mindoro",
        "tips to save in oriental mindoro",
        "pera para sa mindoro",
        "magkano pumunta sa oriental mindoro",
        "magkano ferry sa mindoro",
        "how much $ for mindoro",
        "budget trevl mindoro",
    ],

    "Accommodation_Types": [
        "accommodation in oriental mindoro",
        "places to sleep in oriental mindoro",
        "sleep in oriental mindoro",
        "overnight in oriental mindoro",
        "hotel options oriental mindoro",
        "what hotel to choose in oriental mindoro",
        "best hotel in oriental mindoro",
        "top hotels oriental mindoro",
        "recommended hotel oriental mindoro",
        "luxury hotel oriental mindoro",
        "5 star hotel mindoro",
        "budget hotel mindoro",
        "cheap hotel mindoro",
        "affordable accommodation mindoro",
        "hostel mindoro",
        "backpacker hostel mindoro",
        "dorm room mindoro",
        "bed and breakfast mindoro",
        "pension house oriental mindoro",
        "guesthouse oriental mindoro",
        "airbnb mindoro",
        "vacation rental mindoro",
        "beach resort mindoro",
        "inland resort mindoro",
        "family resort oriental mindoro",
        "couple resort mindoro",
        "resort with pool mindoro",
        "beachfront accommodation mindoro",
        "mountain lodge mindoro",
        "eco lodge mindoro",
        "camping site mindoro",
        "campsite oriental mindoro",
        "tent camping mindoro",
        "glamping mindoro",
        "hotel in calapan city",
        "hotel in puerto galera",
        "hotel in naujan",
        "hotel near naujan lake",
        "hotel in baco",
        "hotel in pinamalayan",
        "inn in oriental mindoro",
        "motel oriental mindoro",
        "transient house mindoro",
        "where can i book a hotel in mindoro",
        "online hotel booking mindoro",
        "book accommodation mindoro",
        "check in mindoro hotel",
        "room for rent mindoro",
        "saan matutulog sa oriental mindoro",
        "hotel near the beach mindoro",
        "overnight stay mindoro",
        "accomodation mindoro",
        "acommodation mindoro",
    ],

    "Booking_Help": [
        "i want to book",
        "how can i book",
        "can i book here",
        "i need to make a booking",
        "help me book a hotel",
        "help me reserve",
        "how to reserve a hotel room",
        "how do i make a reservation",
        "steps to book a hotel",
        "guide to booking on lakbay",
        "lakbay hotel booking",
        "hotel reservation on lakbay",
        "booking on this app",
        "how to use the booking feature",
        "reserve hotel on this app",
        "book a resort mindoro",
        "book accommodation on lakbay",
        "i want to reserve",
        "reservation tutorial",
        "confirm my booking",
        "booking confirmation",
        "where is my booking",
        "view my bookings",
        "cancel my booking",
        "how to cancel a reservation",
        "change my booking",
        "modify reservation",
        "booking error",
        "problem with booking",
        "booking not working",
        "how to pay for hotel",
        "payment for booking",
        "secure a room",
        "check availability lakbay",
        "availability of rooms",
        "is there a room available",
        "choose check in date",
        "choose check out date",
        "number of guests",
        "book for 2 guests",
        "book for family",
        "book for 3 nights",
        "how to book a tour",
        "book a tour on lakbay",
        "book an activity",
        "reserve a tour slot",
        "tour booking help",
        "tour reservation help",
        "how to complete booking",
        "finish the booking",
        "paano mag reserve ng hotel",
        "i wanna book",
        "how 2 book",
        "boking help",
    ],

    "App_Capabilities": [
        "tell me what you can do",
        "what can this chatbot help with",
        "what topics can you answer",
        "what do you know",
        "what are you capable of",
        "how can this app help me",
        "help me understand what lakbay does",
        "lakbay app capabilities",
        "what is lakbay for",
        "why use lakbay",
        "what is the purpose of lakbay",
        "what can lakbay do for me",
        "lakbay travel app",
        "what services lakbay provides",
        "what does this chatbot know",
        "questions you can answer",
        "topics this chatbot covers",
        "ask the chatbot",
        "chatbot help",
        "chatbot guide",
        "what does the app offer",
        "features in lakbay app",
        "list of features",
        "all features of lakbay",
        "does lakbay have hotel booking",
        "does lakbay have maps",
        "does lakbay have ar tour",
        "language support lakbay",
        "languages in lakbay",
        "multilingual chatbot",
        "how many languages does lakbay support",
        "ar 360 tour feature",
        "virtual tour feature lakbay",
        "itinerary feature lakbay",
        "does lakbay have itinerary",
        "plan my trip on lakbay",
        "trip planner lakbay",
        "is lakbay free",
        "how to use lakbay",
        "guide to using lakbay",
        "lakbay user guide",
        "who made lakbay",
        "who developed lakbay",
        "lakbay developers",
        "contact lakbay support",
        "customer service lakbay",
        "report a problem lakbay",
        "lakbay review",
        "ano ang lakbay",
        "ano ang kaya ng chatbot",
        "what can u do",
        "what do u know",
        "app fetures",
    ],

    "Safety_Emergency": [
        "emergency number in oriental mindoro",
        "emergency hotline mindoro",
        "who to call in emergency mindoro",
        "ambulance number oriental mindoro",
        "hospital number oriental mindoro",
        "police emergency mindoro",
        "fire emergency mindoro",
        "coast guard number mindoro",
        "emergency services oriental mindoro",
        "medical emergency oriental mindoro",
        "rescue mindoro",
        "accident in oriental mindoro",
        "robbery what to do oriental mindoro",
        "help in emergency in mindoro",
        "what number to call in emergency",
        "911 mindoro",
        "911 in oriental mindoro",
        "emergency procedures mindoro",
        "safety precautions oriental mindoro",
        "how to stay safe in oriental mindoro",
        "travel safety advice mindoro",
        "is mindoro dangerous",
        "crime rate oriental mindoro",
        "safe to travel to mindoro",
        "safety in puerto galera at night",
        "safe at night oriental mindoro",
        "pickpocket mindoro",
        "scam warning oriental mindoro",
        "tourist scam mindoro",
        "hospital in calapan",
        "hospital near nautjan lake",
        "nearest hospital in oriental mindoro",
        "medical clinic oriental mindoro",
        "pharmacy oriental mindoro",
        "first aid kit mindoro",
        "water safety mindoro",
        "sea safety mindoro",
        "jellyfish sting mindoro",
        "sea urchin mindoro",
        "water rescue mindoro",
        "typhoon warning mindoro",
        "what to do if typhoon mindoro",
        "coast guard puerto galera",
        "rescue boat mindoro",
        "lifeguard beach mindoro",
        "travel insurance mindoro",
        "safe hiking mindoro",
        "mountain rescue mindoro",
        "emergency contact list mindoro",
        "emer gency mindoro",
        "emrgency number mindoro",
        "safty tips mindoro",
    ],

    "Shopping_Souvenirs": [
        "buy souvenirs in oriental mindoro",
        "where to buy souvenirs",
        "souvenir shop mindoro",
        "souvenir store oriental mindoro",
        "local products to buy in oriental mindoro",
        "things to buy in mindoro",
        "gifts from oriental mindoro",
        "pasalubong oriental mindoro",
        "bring home from mindoro",
        "best pasalubong mindoro",
        "popular souvenirs mindoro",
        "what to bring home from mindoro",
        "local crafts oriental mindoro",
        "handicrafts oriental mindoro",
        "artisanal products mindoro",
        "handmade goods mindoro",
        "authentic local products mindoro",
        "mangyan handicrafts where to buy",
        "mangyan baskets shop",
        "mangyan bags for sale",
        "abaca products mindoro",
        "rattan products mindoro",
        "woven basket mindoro",
        "organic products mindoro",
        "coconut products mindoro",
        "honey oriental mindoro",
        "local honey mindoro",
        "dried fish souvenir mindoro",
        "kakanin to bring home",
        "native sweets mindoro",
        "delicacies mindoro",
        "shell jewelry mindoro",
        "wooden crafts mindoro",
        "bamboo products mindoro",
        "calapan public market shopping",
        "market shopping oriental mindoro",
        "mall in calapan",
        "tiangge mindoro",
        "ukay ukay mindoro",
        "flea market mindoro",
        "online shopping mindoro products",
        "e commerce mindoro",
        "buy mindoro products online",
        "shop at calapan market",
        "santo nino market calapan",
        "saturday market mindoro",
        "sunday market mindoro",
        "cheap souvenirs mindoro",
        "saan bibilhin ang pasalubong sa mindoro",
        "pasalubong sa mindoro",
        "shoping mindoro",
        "souvenirs to buy",
    ],

    "History_Heritage": [
        "history of mindoro",
        "mindoro history",
        "historical facts about oriental mindoro",
        "colonial era mindoro",
        "spanish era mindoro",
        "american era mindoro",
        "world war 2 in oriental mindoro",
        "japanese occupation mindoro",
        "battle of mindoro",
        "pre colonial mindoro",
        "ancient mindoro",
        "early history oriental mindoro",
        "founding of oriental mindoro",
        "origin of oriental mindoro",
        "mindoro in history",
        "timeline mindoro",
        "historical events mindoro",
        "heritage buildings oriental mindoro",
        "old buildings mindoro",
        "colonial buildings mindoro",
        "heritage structures mindoro",
        "churches in oriental mindoro",
        "old churches oriental mindoro",
        "sto nino cathedral calapan visit",
        "santo nino cathedral history",
        "historic church calapan",
        "shrine in oriental mindoro",
        "monument oriental mindoro",
        "historical landmark mindoro",
        "heritage museum oriental mindoro",
        "oriental mindoro museum",
        "cultural heritage mindoro",
        "heritage sites to visit mindoro",
        "ruins mindoro",
        "old ruins mindoro",
        "historical site mindoro",
        "heritage trail mindoro",
        "century old church mindoro",
        "heritage walk mindoro",
        "old school in oriental mindoro",
        "established municipalities mindoro",
        "first settlement mindoro",
        "mangyan history",
        "indigenous history mindoro",
        "mindoreño culture",
        "local history oriental mindoro",
        "how was oriental mindoro established",
        "kasaysayan ng oriental mindoro",
        "history ng mindoro",
        "histori mindoro",
        "historiy of mindoro",
    ],

    "Naujan_Lake_Wildlife": [
        "wildlife in naujan lake",
        "animals in naujan",
        "birds in naujan",
        "birdwatching in naujan",
        "birds to see in naujan lake",
        "what birds live in naujan lake",
        "birds of naujan lake national park",
        "philippine duck in naujan",
        "endangered birds naujan lake",
        "migratory birds naujan",
        "siberian birds naujan lake",
        "birds from siberia naujan lake",
        "freshwater birds mindoro",
        "wetland birds oriental mindoro",
        "herons naujan lake",
        "ducks naujan lake",
        "kingfishers naujan lake",
        "crocodile in naujan lake",
        "freshwater crocodile mindoro",
        "crocodile sighting oriental mindoro",
        "monitor lizard naujan",
        "reptiles in naujan lake",
        "amphibians naujan lake",
        "fish in naujan lake",
        "fishing in naujan lake",
        "freshwater fish oriental mindoro",
        "maliputo fish naujan",
        "tilapia naujan lake",
        "mudfish oriental mindoro",
        "ecology of naujan lake",
        "ecosystem naujan lake",
        "biodiversity in naujan",
        "nature reserve naujan",
        "ramsar wetland mindoro",
        "wetland ecology oriental mindoro",
        "conservation naujan lake",
        "national park naujan lake",
        "naujan lake national park guide",
        "how to go to naujan lake national park",
        "tour naujan lake",
        "boat ride naujan lake",
        "fishing tour naujan lake",
        "birdwatching tour naujan lake",
        "nature tour naujan lake",
        "guides for naujan lake",
        "entrance fee naujan lake",
        "permit naujan national park",
        "wild life naujan",
        "wildlif naujan",
        "birdwatching naujan lak",
    ],

    "Eco_Tourism": [
        "eco tourism in oriental mindoro",
        "sustainable tourism oriental mindoro",
        "responsible tourism oriental mindoro",
        "environmental tourism mindoro",
        "green travel oriental mindoro",
        "nature based tourism oriental mindoro",
        "ecological tour mindoro",
        "eco friendly mindoro",
        "environmentally friendly travel mindoro",
        "support local tourism mindoro",
        "community based tourism mindoro",
        "support indigenous community mindoro",
        "conservation travel oriental mindoro",
        "nature conservation mindoro",
        "wildlife conservation mindoro",
        "coral reef conservation mindoro",
        "mangrove conservation mindoro",
        "tree planting mindoro",
        "clean up drive mindoro",
        "environmental programs oriental mindoro",
        "protect nature in mindoro",
        "nature park mindoro",
        "nature reserve in mindoro",
        "protected area oriental mindoro",
        "apo reef national park eco tour",
        "naujan lake eco tour",
        "mount halcon eco zone",
        "mangrove tour oriental mindoro",
        "mangrove walk mindoro",
        "mangrove forest mindoro",
        "bird sanctuary mindoro",
        "wildlife sanctuary oriental mindoro",
        "organic farm mindoro",
        "agri eco tourism mindoro",
        "farm tour mindoro",
        "rice farm visit mindoro",
        "coconut farm visit mindoro",
        "eco lodge stay mindoro",
        "eco friendly resort mindoro",
        "zero waste travel mindoro",
        "offsetting carbon mindoro",
        "low impact travel mindoro",
        "leave no trace mindoro",
        "hiking with nature guide mindoro",
        "guided nature walk mindoro",
        "educational nature tour",
        "school field trip mindoro nature",
        "sustainabl travel",
        "eco turism mindoro",
        "nature tour mindoro",
    ],
}


def load_intents():
    with open(INTENTS_FILE, "r", encoding="utf-8") as f:
        return json.load(f)


def save_intents(data):
    with open(INTENTS_FILE, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)


def add_patterns():
    data = load_intents()
    stats = {}

    for intent in data["intents"]:
        tag = intent["tag"]
        if tag in EXTRA_PATTERNS:
            before = len(intent["patterns"])
            existing = set(p.lower() for p in intent["patterns"])
            new_patterns = [
                p for p in EXTRA_PATTERNS[tag]
                if p.lower() not in existing
            ]
            intent["patterns"].extend(new_patterns)
            after = len(intent["patterns"])
            stats[tag] = (before, after)

    save_intents(data)

    print("Pattern expansion complete!\n")
    print(f"{'Intent':<40} {'Before':>8} {'After':>7} {'Added':>7}")
    print("-" * 65)
    for tag, (before, after) in sorted(stats.items()):
        print(f"{tag:<40} {before:>8} {after:>7} {after-before:>7}")
    total_added = sum(after - before for before, after in stats.values())
    print(f"\nTotal patterns added: {total_added}")


if __name__ == "__main__":
    add_patterns()
