const ABOUT_COPY = {
  en: {
    fieldGuide: 'A field guide to place', mastheadTitle: 'Meet Naujan', mastheadLede: 'A living municipality shaped by water, soil, memory, and the people who call Oriental Mindoro home.',
    follow: 'Follow the thread', moreThan: 'A place is more than a pin on a map.', journeyText: 'Move through Naujan by following the connections between landscape, people, memory, and invitation.',
    land: 'The land', landTitle: 'Water and soil', people: 'The people', peopleTitle: 'Many roots, one home', memory: 'The memory', memoryTitle: 'Stories in stone', invitation: 'The invitation', invitationTitle: 'Come closer', exploreStory: 'Explore story',
    voices: 'Voices of Naujan', listen: 'Listen to the place.', nextChapter: 'Your next chapter', slower: 'Make room for a slower kind of discovery.', visitText: 'Use the map to find places to pause, then pair your route with a stay and an experience.', map: 'Open the map', itinerary: 'Build an itinerary', attractions: 'Browse attractions', accomplishmentLabel: 'The work behind the welcome', accomplishmentTitle: 'Accomplishments & Milestones'
  },
  es: { fieldGuide: 'Una guia del lugar', mastheadTitle: 'Conoce Naujan', mastheadLede: 'Un municipio vivo formado por el agua, la tierra, la memoria y las personas de Oriental Mindoro.', follow: 'Sigue el hilo', moreThan: 'Un lugar es mas que un punto en el mapa.', journeyText: 'Recorre Naujan siguiendo las conexiones entre paisaje, personas, memoria e invitacion.', land: 'La tierra', landTitle: 'Agua y suelo', people: 'Las personas', peopleTitle: 'Muchas raices, un hogar', memory: 'La memoria', memoryTitle: 'Historias en piedra', invitation: 'La invitacion', invitationTitle: 'Acercate', exploreStory: 'Explorar historia', voices: 'Voces de Naujan', listen: 'Escucha el lugar.', nextChapter: 'Tu proximo capitulo', slower: 'Descubre sin prisa.', visitText: 'Usa el mapa para encontrar lugares donde hacer una pausa.', map: 'Abrir mapa', itinerary: 'Crear itinerario', attractions: 'Ver atracciones', accomplishmentLabel: 'El trabajo detras de la bienvenida', accomplishmentTitle: 'Logros y momentos importantes' },
  tl: { fieldGuide: 'Gabay sa lugar', mastheadTitle: 'Kilalanin ang Naujan', mastheadLede: 'Isang buhay na bayan na hinubog ng tubig, lupa, alaala, at mga taong tumatawag sa Oriental Mindoro na tahanan.', follow: 'Sundan ang kwento', moreThan: 'Ang isang lugar ay higit pa sa isang tuldok sa mapa.', journeyText: 'Tuklasin ang Naujan sa ugnayan ng kalikasan, mga tao, alaala, at paanyaya.', land: 'Ang lupa', landTitle: 'Tubig at lupa', people: 'Ang mga tao', peopleTitle: 'Maraming ugat, iisang tahanan', memory: 'Ang alaala', memoryTitle: 'Mga kwento sa bato', invitation: 'Ang paanyaya', invitationTitle: 'Lumapit', exploreStory: 'Tuklasin ang kwento', voices: 'Mga tinig ng Naujan', listen: 'Pakinggan ang lugar.', nextChapter: 'Ang susunod mong kabanata', slower: 'Maglaan ng oras sa pagtuklas.', visitText: 'Gamitin ang mapa upang makahanap ng mga lugar na maaaring pahingahan.', map: 'Buksan ang mapa', itinerary: 'Gumawa ng itineraryo', attractions: 'Tingnan ang mga atraksyon', accomplishmentLabel: 'Ang gawa sa likod ng pagtanggap', accomplishmentTitle: 'Mga Nagawa at Mahahalagang Yugto' },
  zh: { fieldGuide: '地方指南', mastheadTitle: '认识瑙汉', mastheadLede: '这里由水、土地、记忆以及把东方民都洛称为家的人们共同塑造。', follow: '沿着故事前行', moreThan: '一个地方不只是地图上的一个点。', journeyText: '沿着土地、人们、记忆与邀请之间的联系探索瑙汉。', land: '土地', landTitle: '水与土壤', people: '人们', peopleTitle: '多种根源，一个家', memory: '记忆', memoryTitle: '石头里的故事', invitation: '邀请', invitationTitle: '走近一些', exploreStory: '探索故事', voices: '瑙汉之声', listen: '聆听这片土地。', nextChapter: '你的下一章', slower: '给慢慢发现留出空间。', visitText: '使用地图寻找可以停留的地方。', map: '打开地图', itinerary: '创建行程', attractions: '浏览景点', accomplishmentLabel: '欢迎背后的努力', accomplishmentTitle: '成就与里程碑' }
};

export const aboutCopy = (language, key, fallback) => ABOUT_COPY[language]?.[key] || ABOUT_COPY.en[key] || fallback || key;
